version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./acl.conf:/mosquitto/config/acl.conf:ro
      - ./passwd:/mosquitto/config/passwd
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  stb-manager:
    image: ghcr.io/kingiu/stb-manager/stb-manager:latest
    container_name: stb-manager
    network_mode: host
    volumes:
      - ./ota:/opt/ota
    environment:
      - MQTT_BROKER=tcp://127.0.0.1:1883
      - MQTT_USER=admin
      - MQTT_PASS=admin@manager
      - HTTP_PORT=8080
      - OTA_DIR=/opt/ota
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
