services:
  stb-manager:
    image: ghcr.io/kingiu/stb-manager/stb-manager:latest
    container_name: stb-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./ota:/opt/ota
    environment:
      - MQTT_BROKER=tcp://127.0.0.1:1883
      - MQTT_USER=gk-admin
      - MQTT_PASS=gk-stb-2024
      - HTTP_PORT=8080
      - OTA_DIR=/opt/ota
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
