#!/system/bin/sh
IFACE=eth0
MODE=v4
USER=""
PASSWORD=""

TIMES=2
WAIT_TIME=5

MTU=1492
MRU=1492

DNS=usepeerdns

IFACE=`getprop net.pppoe.ifname`
MODE=`getprop persist.gk.pppoe.mode`
USER=`getprop net.pppoe.user`
PASSWORD=`getprop net.pppoe.passwd`
