# mosquitto 配置
listener 1883
allow_anonymous false

# 密码文件 (默认密码: admin@manager)
# mosquitto_passwd -c /mosquitto/config/passwd admin
password_file /mosquitto/config/passwd

# ACL 策略
acl_file /mosquitto/config/acl.conf
